/*
 * GeoPolitik world generator.
 *
 * Phase 2 ships a curated test fixture (75 nations, 750 cities, hand-picked
 * efficiency multipliers) generated by `scripts/fetch-test-cities.ts` from the
 * GeoNames CC-BY 4.0 dataset; the output lands in `packages/world-data` and is
 * wired into Drizzle migration 0002_test_world_seed.sql.
 *
 * Phase 1 (per ROADMAP.md) replaces this fixture with a full OSM-driven
 * pipeline: Geofabrik extracts -> PostGIS precompute -> SQL+JSON dump.
 */

import { parseArgs } from "node:util";

const { values } = parseArgs({
	args: Bun.argv.slice(2),
	options: {
		preset: { type: "string", default: "test-fixture" },
		help: { type: "boolean", short: "h", default: false },
	},
	allowPositionals: false,
});

if (values.help) {
	console.log(`
geopolitik-worldgen

Usage:
  bun run worldgen --preset=<name>

Presets:
  test-fixture    (Phase 2) regenerate the 75-nation GeoNames test world
                  -> equivalent to: bun run --cwd apps/worldgen fetch:test-cities
  earth-small     (Phase 1, NOT YET IMPLEMENTED) ~30 countries, ~500 cities
  europe          (Phase 1, NOT YET IMPLEMENTED) European theatre only

The Phase 2 test fixture is committed under packages/world-data/test-world.json
plus the seed migration; you only need to re-run this command if the upstream
GeoNames snapshot has changed and you want to refresh the fixture.
`);
	process.exit(0);
}

if (values.preset === "test-fixture") {
	console.log("[worldgen] Regenerating Phase 2 test fixture from GeoNames…");
	await import("../scripts/fetch-test-cities");
} else {
	console.error(`[worldgen] preset='${values.preset}' is not yet implemented (Phase 1 work).`);
	process.exit(1);
}
