/**
 * ISO 3166-1 alpha-3 → alpha-2 lookup for the countries shipped in the Phase 2
 * worldgen fixture. Used to render `flag-icons` SVGs (which take alpha-2).
 *
 * Extend this map when worldgen adds new countries. Unknown codes return null
 * and the `<NationFlag>` component renders a neutral placeholder.
 */
export const ALPHA3_TO_ALPHA2: Record<string, string> = {
	AFG: "af",
	AGO: "ao",
	ARG: "ar",
	AUS: "au",
	BFA: "bf",
	BGD: "bd",
	BRA: "br",
	CAN: "ca",
	CHL: "cl",
	CHN: "cn",
	CIV: "ci",
	CMR: "cm",
	COD: "cd",
	COL: "co",
	DEU: "de",
	DZA: "dz",
	ECU: "ec",
	EGY: "eg",
	ESP: "es",
	ETH: "et",
	FRA: "fr",
	GBR: "gb",
	GHA: "gh",
	GIN: "gn",
	GTM: "gt",
	IDN: "id",
	IND: "in",
	IRN: "ir",
	IRQ: "iq",
	ITA: "it",
	JPN: "jp",
	KAZ: "kz",
	KEN: "ke",
	KHM: "kh",
	KOR: "kr",
	LKA: "lk",
	MAR: "ma",
	MDG: "mg",
	MEX: "mx",
	MLI: "ml",
	MMR: "mm",
	MOZ: "mz",
	MWI: "mw",
	MYS: "my",
	NER: "ne",
	NGA: "ng",
	NLD: "nl",
	NPL: "np",
	PAK: "pk",
	PER: "pe",
	PHL: "ph",
	POL: "pl",
	PRK: "kp",
	ROU: "ro",
	RUS: "ru",
	SAU: "sa",
	SDN: "sd",
	SEN: "sn",
	SOM: "so",
	SYR: "sy",
	TCD: "td",
	THA: "th",
	TUR: "tr",
	TWN: "tw",
	TZA: "tz",
	UGA: "ug",
	UKR: "ua",
	USA: "us",
	UZB: "uz",
	VEN: "ve",
	VNM: "vn",
	YEM: "ye",
	ZAF: "za",
	ZMB: "zm",
	ZWE: "zw",
};

export function alpha3ToAlpha2(code: string): string | null {
	return ALPHA3_TO_ALPHA2[code.toUpperCase()] ?? null;
}
